Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial64'
  config.vm.box_check_update = false

  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.synced_folder '../build', '/var/www/endless_ships'

  config.vm.provision :shell, inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
  SHELL

  config.vm.provision :file, source: 'endless_ships', destination: 'default'

  config.vm.provision :shell, inline: <<-SHELL
    mv /home/ubuntu/default /etc/nginx/sites-available/default
    /etc/init.d/nginx reload
  SHELL
end
